### ISSUE TITLE
Error running jspm build: "Error: Cannot find module 'process'"

### ISSUE THREAD

**Issue by nimajneb** [systemjs/plugin-babel#58]
Hi,

I'm trying to build a static version of an application using jspm 0.17-beta.27 and plugin-babel 0.0.13. On my development system everything works just fine, but when I try to run the build process on the target system, I can't seem to get it to work.

To reproduce, I assembled a test case here: https://github.com/nimajneb/jspm-babel-test

```
$ jspm build src/app.js 
     Creating the single-file build for src/app.js...

err  (SystemJS) module.js:338
      throw err;
      ^
  Cannot find module 'process'
  module.js:338
      throw err;
      ^
  Error: Cannot find module 'process'
      at Function.Module._resolveFilename (module.js:336:15)
      at Function.Module._load (module.js:278:25)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at p (/home/benjamin/jspm-babel-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:1:3125)
      at i (/home/benjamin/jspm-babel-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:1:1851)
      at /home/benjamin/jspm-babel-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:1:2261
      at /home/benjamin/jspm-babel-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:41360:17
      at l (/home/benjamin/jspm-babel-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:1:2183)
      at i (/home/benjamin/jspm-babel-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:1:1817)
      at /home/benjamin/jspm-babel-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:1:2261
      at /home/benjamin/jspm-babel-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:9943:17
      at l (/home/benjamin/jspm-babel-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:1:2183)
      at a (/home/benjamin/jspm-babel-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:1:959)
      at p (/home/benjamin/jspm-babel-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:1:3198)
      at /home/benjamin/jspm-babel-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:1:4104
  Evaluating /home/benjamin/jspm-babel-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/plugin-babel.js
  Error loading /home/benjamin/jspm-babel-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/plugin-babel.js
```

The target system only has node 0.12.2 and npm 3.3.4 installed, whereas on my development system I use node 5.9.0 and npm 3.8.3. However, I couldn't find any information on minimum requirements of the babel plugin. Could that be an issue?

Cheers,
Benjamin

**Comment by guybedford** [comment]
jspm 0.17 does require Node 4 or Node 6.
