### ISSUE TITLE
doing jspm install doesn't seem to also install the needed buffer@4.9.1

### ISSUE THREAD

**Issue by davis** [systemjs/plugin-babel#59]
![screen shot 2016-09-07 at 5 56 07 pm](https://cloud.githubusercontent.com/assets/4855619/18333490/61f389fe-7524-11e6-8095-07516afb7e43.png)

**Comment by davis** [comment]
on an unrelated note, in the releases the version is 0.14.0, but the one installed during jspm install is 0.0.14

**Comment by andyearnshaw** [comment]
Just about to report the same, 0.0.13 is fine but 0.0.14 gives us this error when used with intern-systemjs-loader.

**Comment by Bodom78** [comment]
Ran into the same issue, using 0.0.13 works for the time being.

**Comment by blittle** [comment]
A temporary workaround: `jspm install npm:buffer@4.9.1`

**Comment by leepowellcouk** [comment]
Getting the same error, but I'm not using JSPM, and manually installing buffer@4.9.1 doesn't seem to solve the issue.

    http://localhost:3000/node_modules/buffer@4.9.1
	Error: XHR error (404 Not Found) loading http://localhost:3000/node_modules/buffer@4.9.1
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:636:29)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:225:37)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:125:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:293:33)
	Error loading http://localhost:3000/node_modules/buffer@4.9.1 as "npm:buffer@4.9.1" from http://localhost:3000/node_modules/systemjs-plugin-babel/systemjs-babel-browser.js
	Unable to load transpiler to transpile http://localhost:3000/app/main.js
	Error loading http://localhost:3000/app/main.js ; Zone: <root> ; Task: Promise.then ; Value: Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/buffer@4.9.1(…) (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/buffer@4.9.1
	Error: XHR error (404 Not Found) loading http://localhost:3000/node_modules/buffer@4.9.1
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:636:29)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:225:37)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:125:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:293:33)
	Error loading http://localhost:3000/node_modules/buffer@4.9.1 as "npm:buffer@4.9.1" from http://localhost:3000/node_modules/systemjs-plugin-babel/systemjs-babel-browser.js
	Unable to load transpiler to transpile http://localhost:3000/app/main.js
	Error loading http://localhost:3000/app/main.js

**Comment by guybedford** [comment]
This was a regression in SystemJS builder which has been fixed now in https://github.com/systemjs/builder/commit/e888dfa8f41dacea7b9924ef40c4d9b451798840.

I've published a new 0.0.15 release of the plugin with the fix.
