### ISSUE TITLE
applyMap -- undefined is not a function

### ISSUE THREAD

**Issue by steveaft** [systemjs/plugin-babel#7]
When I run jspm install plugin-babel I keep getting this error:

(I added some console.log statements in build.js line 251)

```$ ./node_modules/.bin/jspm  install plugin-babel
     Updating registry cache...
     Looking up npm:systemjs-plugin-babel
     Downloading npm:systemjs-plugin-babel@0.0.2
**map  { 'systemjs-babel-build':
   { browser: './systemjs-babel-browser.js',
     node: './systemjs-babel-node.js' } }
 m in map  systemjs-babel-build**

err  TypeError: undefined is not a function
         at applyMap (/Users/.../node_modules/jspm/lib/build.js:252:15)
         at /Users/.../node_modules/jspm/lib/build.js:528:30
         at String.replace (native)

warn Installation changes not saved.'```

btw, What would you consider a clean install if I were going to try this from scratch?
Something like this?:
    npm install systemjs
    npm install jspm
    jspm install plugin-babel

**Comment by guybedford** [comment]
Thanks, yes the Babel plugin is not compatible with jspm 0.16.
