### ISSUE TITLE
TypeError: Cannot read property 'bgRed' of undefined

### ISSUE THREAD

**Issue by mauron85** [systemjs/plugin-babel#81]
Hi there, 

thank you for this very useful plugin. Not sure if I'm doing something wrong but I've got following bundle compilation error:

I think it has to do something with chalk, it seems that it doesn't have property `chalk.white.bgRed.bold` (used in  `function getDefs(chalk){...}` of `systemjs-babel-node.js`. I guess chalk is included in `systemjs-babel-node.js` so there is not much I can do, or?

```
Build error
{ (SystemJS) Cannot read property 'bgRed' of undefined
	TypeError: Cannot read property 'bgRed' of undefined
	    at getDefs (/home/finch/dev/mapilary/react-console/utils/plugin-babel-master/systemjs-babel-node.js:30631:27)
	    at exports.default (/home/finch/dev/mapilary/react-console/utils/plugin-babel-master/systemjs-babel-node.js:30563:16)
	    at File.wrap (/home/finch/dev/mapilary/react-console/utils/plugin-babel-master/systemjs-babel-node.js:14164:56)
	    at Pipeline.transform (/home/finch/dev/mapilary/react-console/utils/plugin-babel-master/systemjs-babel-node.js:14378:19)
	    at /home/finch/dev/mapilary/react-console/utils/jspm_packages/npm/systemjs-plugin-babel@0.0.23/plugin-babel.js:173:24
	Error loading /home/finch/dev/mapilary/react-console/src/root/entrance/LoginPage.jsx as "./root/entrance/LoginPage" from /home/finch/dev/mapilary/react-console/src/login.jsx
  originalErr: 
   TypeError: Cannot read property 'bgRed' of undefined
       at getDefs (file:///home/finch/dev/mapilary/react-console/utils/plugin-babel-master/systemjs-babel-node.js:30631:27)
       at exports.default (file:///home/finch/dev/mapilary/react-console/utils/plugin-babel-master/systemjs-babel-node.js:30563:16)
       at File.wrap (file:///home/finch/dev/mapilary/react-console/utils/plugin-babel-master/systemjs-babel-node.js:14164:56)
       at Pipeline.transform (file:///home/finch/dev/mapilary/react-console/utils/plugin-babel-master/systemjs-babel-node.js:14378:19)
       at file:///home/finch/dev/mapilary/react-console/utils/jspm_packages/npm/systemjs-plugin-babel@0.0.23/plugin-babel.js:173:24 }
```

config.js

**Comment by guybedford** [comment]
Thanks, I believe I've fixed this in 0.0.24.
